title: Open Earth Project
logo: /assets/img/LB_Color_Wordmark.png
description: Students exploring the intersection of science with public policy by building and operating remote-sensing spacecraft.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
